name: arb_utils
description: A set of tools to work with .arb files (the preferred Dart way of dealing with i18n/l10n/translations)
version: 0.9.0
repository: https://github.com/Rodsevich/arb_utils
homepage: https://gitlab.com/Rodsevich/arb_utils

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^2.4.2
  collection: ^1.18.0
  intl: ">=0.18.0 <0.20.0"
  intl_utils: ^2.8.7
  shared_preferences: ^2.2.2
  dcli: ^7.0.3
  dart_console: ^4.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.2
  win32: ^5.4.0

executables:
  arb_utils:
