name: arb_utils
description: A set of tools to work with .arb files (the preferred Dart way of dealing with i18n/l10n/translations)
version: 0.4.0
repository: https://github.com/Rodsevich/arb_utils
homepage: https://gitlab.com/Rodsevich/arb_utils

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^2.3.0
  collection: ^1.15.0
  intl: ^0.17.0
  intl_utils: ^2.6.1
  shared_preferences: ^2.0.15
  dcli: ^1.35.4

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.7

executables:
  arb_utils:
